### ISSUE TITLE
(1) Different sample counts, (2) duplicated tweets and (3) missing fold information

### ISSUE THREAD

**Issue by trtm** [LCS2-IIITD/LESA-EACL-2021#1]
Dear authors, 

I was currently reading your [“LESA” paper]( https://arxiv.org/abs/2101.11891 ) and I really liked your approach! 

(1) However, looking at the [Twitter data](https://github.com/LCS2-IIITD/LESA-EACL-2021/blob/main/data/Twitter.csv) in the Github repository I was not able to get the same count of tweets as you reported in your work. 
I read them with Python’s pandas library and use the “,” as a separator and I count 9981 tweets, whereas you report 9894 tweets. 

```python
TWTR_df = pd.read_csv('Twitter.csv', sep=',', converters={'tweet_id': str})
len(TWTR_df)
```

Am I missing something else? 

(2) Furthermore, it appears that 396 tweet_ids are duplicates, while their corresponding tweet_text are (slightly) different. (Usually one of them looks like a pre-processed tweet of the other) 

```python
grouped = TWTR_df.loc[TWTR_df.tweet_id!='nan'][['tweet_id','claim']].groupby('tweet_id').count()
len(grouped.loc[grouped.claim>1])
```

For instance for the ```tweet_id="1247599282779312136"``` there are two tweet_text with exactly the same beginning but with different claim labels. 

1, example: claim label: 1  ```The only "CURE" of Corona is to "CARE".  #CoronavirusPandemic #coronavirus #CoronaFreePakistan #Coronaturkey #CoronaInPakistan``` 

2, example: claim label: 0  ```The only CURE" of Corona is to "CARE".``` 

(3) Last but not least, can you please provide the fold information (train, eval, test splits), since it is currently missing in the repository.

Any help would be appreciated, since I think your data set is really important and could potentially be helpful in my own research! 

I would like to evaluate models, trained on this corpus, in some other studies.

I hope to hear soon from you! 
All the best and stay safe, 
Dietrich

**Comment by ShreyaGupta08** [comment]
Hi Dietrich,

Thank you for bringing it to our attention. Since these are multi-level issues, I'm segregating them and opening them as separate issues to resolve them systematically. I'll close this issue and open three new ones and address them individually. Hope this works.

**Comment by trtm** [comment]
Any update on that?
